# Generated by Django 3.2.7 on 2022-03-03 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('classifieds', '0001_initial'),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion.type'),
        ),
        migrations.AddField(
            model_name='option',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classifieds.attribute'),
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifieds.category', verbose_name='カテゴリー'),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classifieds.item'),
        ),
        migrations.AddField(
            model_name='category',
            name='field_attributes',
            field=models.ManyToManyField(blank=True, related_name='field_attributes', to='classifieds.Attribute'),
        ),
        migrations.AddField(
            model_name='category',
            name='filter_attributes',
            field=models.ManyToManyField(blank=True, related_name='filter_attributes', to='classifieds.Attribute'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='classifieds.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='promotion.Type'),
        ),
    ]
