# Generated by Django 3.2.7 on 2022-03-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
